"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _game_card from './game-card.bones.json'

registerBones({
  "game-card": _game_card,
})
